[keyboard]

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1~"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[4~"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"
mode = "AppKeypad"

[[keyboard.bindings]]
chars = "\u001B[P"
key = "Delete"
mode = "~AppKeypad"

[[keyboard.bindings]]
chars = "\u001B[65;5u"
key = "A"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[66;5u"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[67;5u"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[68;5u"
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[69;5u"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[70;5u"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[71;5u"
key = "G"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[73;5u"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[77;5u"
key = "M"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[78;5u"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[79;5u"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[80;5u"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[81;5u"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[82;5u"
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[83;5u"
key = "S"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[84;5u"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[85;5u"
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[86;5u"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[87;5u"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[88;5u"
key = "X"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[89;5u"
key = "Y"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[90;5u"
key = "Z"
mods = "Control|Shift"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

